name: Github action
rating: 5
imageUrl: https://github.com/msa-ez/template-axon2/assets/130956306/d8ff35bf-3367-4488-9733-73c7b82670c7
templateName: github-action
description: As a CI/CD service, GitHub Actions automates tasks such as testing, building, and deploying based on code changes within a GitHub repository.
depends:
tags:
  - Frontend
