forEach: Model
fileName: docker-compose.yml
path: for-model/infra
ifDuplicated: merge
---
services:
{{#boundedContextsOfPBC}}
  {{toLowerCase name}}:
    image: ghcr.io/{{scm.org}}/{{toLowerCase projectName}}/{{scm.repo}}:{{scm.tag}}
    ports:
      - 8080:8080
    volumes:
      - ./path/to/{{toLowerCase name}}/config:/app/config
{{/boundedContextsOfPBC}}
