path: for-model/.github/workflows
---
# README
# Check Setting of your repository 
# Setting > Actions > Genernal > Workflow permissions 
# Select of "Read and write Permissions."

name: github-action

#  display name in gihub-action
run-name: ${{ github.actor }} is out building GitHub Actions

# on:
#   push:
#     # Pattern matched against refs/tags
#     tags:        
#       - '**' 

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./Storage/pom.xml
          mvn clean package -f ./manufacture/Factory/pom.xml

      - name: Docker Build and push for Storage
        uses: docker/build-push-action@v4
        with:
          context: ./Storage
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/store-app/storage:latest
            ghcr.io/${{ github.repository_owner }}/store-app/storage:1.0.0
            
      - name: Docker Build and push for Factory
        uses: docker/build-push-action@v4
        with:
          context: ./manufacture/Factory
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/store-app/manufacture-factory:latest
            ghcr.io/${{ github.repository_owner }}/store-app/manufacture-factory:1.0.0
