forEach: Model
fileName: github-action.yml
---
# README
# Check Setting of your repository 
# Setting > Actions > Genernal > Workflow permissions 
# Select of "Read and write Permissions."

name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
        {{#BoundedContext}}
          mvn clean package -f ./{{name}}/pom.xml
        {{/BoundedContext}}

      {{#BoundedContext}}
      - name: Docker Build and push for {{name}}
        uses: docker/build-push-action@v4
        with:
          context: ./Storage
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/store-app/{{name}}:latest
            ghcr.io/${{ github.repository_owner }}/store-app/{{name}}:1.0.0
      {{/BoundedContext}}
     
